# github action for meveto-php-sdk.
name: tests
on: [push, pull_request]
jobs:
  test:
    name: tests-php-${{ matrix.php-versions }}
    runs-on: ${{ matrix.operating-system }}
    strategy:
      fail-fast: false
      matrix:
        operating-system:
          - 'ubuntu-20.04'
        php-versions:
          - '7.0'
          - '7.1'
          - '7.2'
          - '7.3'
          - '7.4'
          - '8.0'
    steps:
      # checkout.
      - name: checkout
        uses: actions/checkout@v2

      # setup php
      - name: setup-php
        uses: shivammathur/setup-php@v2 #https://github.com/shivammathur/setup-php
        with:
          php-version: ${{ matrix.php-versions }}
          extensions: mbstring, dom, fileinfo
          coverage: xdebug #optional

      # composer cache.
      - name: composer-cache-dir
        id: composer-cache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"

      # composer cache (dependencies).
      - name: composer-cache-deps
        uses: actions/cache@v2
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.json') }}
          restore-keys: ${{ runner.os }}-composer-

      # composer install.
      - name: composer-install
        run: composer install --no-progress --prefer-dist --optimize-autoloader

      # tests.
      - name: phpunit
        run: vendor/bin/phpunit --coverage-text

      # codecov.io
      - name: codecov
        run: bash <(curl -s https://codecov.io/bash)
